loop_time: 300
reddit:
  client_id: ""
  client_secret: ""
  user_agent: ""
email:
  port: 465
  smtp_server: ""
  sender_email: ""
  password: ""
flask:
  user_email: ""
  db_url: "mongodb://localhost:27017/"
  db_name: ""